### ISSUE TITLE
Only one barcode available

### ISSUE THREAD

**Issue by AnniAlma** [SydneyUniLibrary/print-slip-report#40]
Hi! 
We'd really like to use the new print slip report app but we are not able to get all the book barcodes to the list which can fulfill the request. If we use Alma's Pick from the shelf -> print slip report -> download Excel we'll get all the books barcodes which are attached to the holdings. When we'll use the Print Slip Report we'll only get one barcode. Is there anyway to fix it? Thanks.

**Comment by SydneyUni-Jim** [comment]
The data is there and including all the barcodes will definitely be possible.

**Comment by SydneyUni-Jim** [comment]
This is blocked by #42 because that is going to change the internal data structure inside the app.

**Comment by SydneyUni-Jim** [comment]
In these situations, the [requested resource object](https://developers.exlibrisgroup.com/alma/apis/docs/xsd/rest_requested_resource.xsd/) has multiple requests and multiple copies in it.

When there are both multiple requests and multiple copies, there is no direct correlation for which request is for which copy.

A copy has `pid`, `barcode` and `link` fields. None of that appears within the request data inside a requested resource object.

«[Retrieve User Title Request](https://developers.exlibrisgroup.com/alma/apis/docs/bibs/R0VUIC9hbG1hd3MvdjEvYmlicy97bW1zX2lkfS9yZXF1ZXN0cy97cmVxdWVzdF9pZH0=/)» and «[Retrieve User Requests per Item](https://developers.exlibrisgroup.com/alma/apis/docs/bibs/R0VUIC9hbG1hd3MvdjEvYmlicy97bW1zX2lkfS9ob2xkaW5ncy97aG9sZGluZ19pZH0vaXRlbXMve2l0ZW1faWR9L3JlcXVlc3Rz/)» both return exactly the same request object.

We're currently using «Retrieve User Title Request» because that's the request link that is the requested resource object.

If we instead use «Retrieve User Requests per Item» then we know which item a request is for. We can construct the url for a «Retrieve User Requests per Item» by appending `/requests` to url in `location.copy[*].link`.

The relationship between requests and copies is many-to-many. Particularly a single request can appear in the response of multiple «Retrieve User Requests per Item» calls. This is the case of a title-level request where the requested resource object has in it all the available copies that could potentially match the request.

When there are many copies but only one request, all the copies are for the same request. Making a single «Retrieve User Title Request» call will give us the request object.

The result of correlating copies with requests will be that each request has a `copies` [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) with the copies for that request.

**Comment by SydneyUni-Jim** [comment]
@AnniAlma. This code of this done. The fix will be available when beta 8 is realised. I'm planning to release beta 8 shortly.

**Comment by AnniAlma** [comment]
Thank you! 👍
